### ISSUE TITLE
setuptools error 

### ISSUE THREAD

**Issue by NinaWelch** [shoopio/shoop#480]
I was trying to set up Shoop and got the following error message:

Command "/Users/nina/myvenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/var/folders/y_/4vf6_qvd66vcwsy1gdg6wh3w0000gn/T/pip-1c9uii4s-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/y_/4vf6_qvd66vcwsy1gdg6wh3w0000gn/T/pip-tgs2pdpk-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/nina/myvenv/include/site/python3.5/shoop" failed with error code 1 in /var/folders/y_/4vf6_qvd66vcwsy1gdg6wh3w0000gn/T/pip-1c9uii4s-build/

I noticed that requirements-doc.txt had setuptools commented out.

I'm new to Python, but I did set up another Django project without errors.

**Comment by NinaWelch** [comment]
Successfully resolved using a Wheel package.

**Comment by suutari-ai** [comment]
Good that you got this sorted out.

Btw. there's also instructions for installing using the wheel. See https://community.shoop.io/forums/t-22/install-with-wheel/

**Comment by NinaWelch** [comment]
Yep, sitä kautta huomasinkin kokeilla ja onnistuin asentamaan Workbench-version. Kokeilin kuitenkin ensin asentaa sen normaaliversion, joka ei onnistunut. SQL asennus onnistui, mutta seuraavassa vaiheessa kävi näin:


(myvenv) Ninas-MacBook-Pro:sample_shop nina$ python manage.py shoop_init
Unknown command: 'shoop_init'

Workbench versio kuitenkin toimii, mutta onko niin, että siihen ei voi lisätä mitään uutta. Sama ongelma esiintyy Cloud-versiossa?

Muuten tosi siisti!

Nina



________________________________

**Comment by suutari-ai** [comment]
```
(myvenv) Ninas-MacBook-Pro:sample_shop nina$ python manage.py shoop_init Unknown command: 'shoop_init'
```

Johtunee siitä, että sulla ei ole Shoopin appit INSTALLED_APPS:ssa. Tarkista, että projektisi settings-tiedostossa on melkolailla vastaava lista INSTALLED_APPS:ssa kuin shoop_workbench:n base_settings.py:ssäkin.  / This probably means that you don't have Shoop apps in INSTALLED_APPS. Check that your project's settings file has similar list of apps in INSTALLED_APPS as in the base_settings.py of the shoop_workbench.

Jos haluat tehdä muutoksia Shooppiin, niin voit tehdä niitä toki addoneillakin, mutta haluanet joka tapauksessa käyttää oikeaa Django-projektia workbenchin sijaan, sillä workbench on tarkoitettu lähinnä testikäyttöön. / If you want to make changes to Shoop, you may use addons too, but you probably want to use a real Django project anyway, since the workbench is meant mainly for testing.

Kiitos palautteesta!
